batch_size: 32
replay_buffer_size: 100000
hidden_layers: 3
hidden_size: 8
learning_rate: 0.001
chkpt_dir: ./dqn/checkpoints
plot_dir: ./dqn/plots
data_dir: ./dqn/data
discount_factor: 0.99
eps: 0.5
eps_decay_rate: 0.99
eps_min: 0.1
eps_decay_steps: 1000
replace_target_network_steps: 1000
epoch_num: 3
env_name: rl-copa
seed: 46746737
use_gpu: true
which_gpu: 0